development:
  adapter: postgresql
  encoding: unicode
  database: juventude
  pool: 5
  username: juventude
  password: juventude
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: juventude
  pool: 5
  username: juventude
  password: juventude
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: juventude
  pool: 5
  username: juventude
  password: juventude
  host: localhost
