# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20140515125121) do

  create_table "dados", :force => true do |t|
    t.string   "codigo"
    t.integer  "ano"
    t.integer  "fxid"
    t.integer  "univ"
    t.integer  "area"
    t.integer  "sexo"
    t.integer  "cor"
    t.integer  "tipo"
    t.float    "analf"
    t.float    "educa"
    t.float    "freq"
    t.float    "nfreq"
    t.float    "freqfund"
    t.float    "freqfund1"
    t.float    "freqfund2"
    t.float    "ncompfund1"
    t.float    "ncompfund2"
    t.float    "nfncompfund1"
    t.float    "nfncompfund2"
    t.float    "nfcompfund1n2"
    t.float    "nfcompfundnfm"
    t.float    "freqmed"
    t.float    "freqmed2"
    t.float    "ncompmed"
    t.float    "nfncompmed"
    t.float    "nfcompmednfs"
    t.float    "freqprof"
    t.float    "freqprof2"
    t.float    "freqprof3"
    t.float    "freqcompsup"
    t.float    "freqcomppos"
    t.float    "ncompsup"
    t.float    "nestntrab"
    t.float    "nestnpea"
    t.float    "nestntrabnfil"
    t.float    "nestnpeanfil"
    t.float    "nestntrabnafaz"
    t.float    "nestnpeanafaz"
    t.float    "nestnpeanfilnafaz"
    t.float    "afaz20"
    t.float    "termfund"
    t.float    "termmed"
    t.float    "termsup"
    t.float    "vivfilocup"
    t.float    "vivfilnocup"
    t.float    "vivfilest"
    t.float    "vivfilnest"
    t.float    "vivfilocupest"
    t.float    "vivfilnocupnest"
    t.float    "vivfilocupaf"
    t.float    "vivfilnocupaf"
    t.float    "vivfilestaf"
    t.float    "vivfilnestaf"
    t.float    "vivfilocupestaf"
    t.float    "vivfilnocupnestaf"
    t.float    "sind"
    t.float    "outrotrab"
    t.float    "v0102"
    t.float    "pea"
    t.float    "idtrab15"
    t.float    "idtrab18"
    t.float    "dese"
    t.float    "desemes"
    t.float    "deseano"
    t.float    "ocup"
    t.float    "ocupano"
    t.float    "jatrab"
    t.float    "ocupano2"
    t.float    "proctrabocup"
    t.float    "outtrabocup"
    t.float    "outtrabocup2"
    t.float    "ocup2anos"
    t.float    "empdom"
    t.float    "scardom"
    t.float    "cprop"
    t.float    "informal"
    t.float    "trabnrem"
    t.float    "sal1"
    t.float    "sal2"
    t.float    "desloc1"
    t.float    "jornadanot"
    t.float    "jornada40"
    t.float    "jornada30"
    t.float    "nocup"
    t.float    "npea"
    t.float    "extpob"
    t.float    "pob"
    t.float    "cb"
    t.float    "cm"
    t.float    "ebia"
    t.float    "alim"
    t.float    "saudebom"
    t.float    "medico"
    t.float    "dentista"
    t.float    "procatend"
    t.float    "recebatend"
    t.float    "esporte"
    t.float    "esporte2"
    t.float    "acamados"
    t.float    "cronica"
    t.float    "nfezativ"
    t.float    "planosaude"
    t.float    "nuncafumou"
    t.float    "fuma"
    t.float    "fumadia"
    t.float    "fuma15"
    t.float    "fuma18"
    t.float    "tentouparar"
    t.float    "naoquerparar"
    t.float    "naofumamais"
    t.float    "fumardoenca"
    t.float    "tv2"
    t.float    "pc2"
    t.float    "violencia"
    t.float    "acidente"
    t.float    "mobilidade"
    t.float    "chefeconj"
    t.float    "filho"
    t.float    "outropar"
    t.float    "famconviv"
    t.float    "nvontadeprop"
    t.float    "mudar"
    t.float    "nsolteiro"
    t.float    "tfn"
    t.float    "celpess"
    t.float    "utilint3"
    t.float    "tv"
    t.float    "tvrad"
    t.float    "dvd"
    t.float    "telc"
    t.float    "tel"
    t.float    "mcp"
    t.float    "mcpint"
    t.float    "moto"
    t.float    "agua"
    t.float    "esco"
    t.float    "aguaesco"
    t.float    "lixo"
    t.float    "aguaescolixo"
    t.float    "dens"
    t.float    "luz"
    t.float    "seg"
    t.float    "segcasa"
    t.float    "segbairro"
    t.float    "segcid"
    t.float    "vitima"
    t.float    "vitimapoli"
    t.float    "conflito"
    t.float    "conflitosol"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "filtros", :force => true do |t|
    t.string   "titulo"
    t.string   "tipo_grafico"
    t.integer  "fxid"
    t.integer  "univ"
    t.integer  "tipo"
    t.integer  "area"
    t.integer  "sexo"
    t.integer  "cor"
    t.string   "grupo"
    t.string   "objetivo"
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
    t.integer  "fonte"
  end

  create_table "temas", :force => true do |t|
    t.string   "titulo"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

  create_table "temas_filtros", :force => true do |t|
    t.integer  "tema_id"
    t.integer  "filtro_id"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

  add_index "temas_filtros", ["filtro_id"], :name => "index_temas_filtros_on_filtro_id"
  add_index "temas_filtros", ["tema_id"], :name => "index_temas_filtros_on_tema_id"

end
