class Pnad < ActiveRecord::Base
  attr_accessible :acamados, :acidente, :afaz20, :agua, :aguaesco, :aguaescolixo, :alim, :analf, :ano, :area, :cb, :celpess, :chefeconj, :cm, :codigo, :conflito, :conflitosol, :cor, :cprop, :cronica, :dens, :dentista, :dese, :deseano, :desemes, :desloc1, :dvd, :ebia, :educa, :empdom, :esco, :esporte, :esporte2, :extpob, :famconviv, :filho, :freq, :freqcomppos, :freqcompsup, :freqfund, :freqfund1, :freqfund2, :freqmed, :freqmed2, :freqprof, :freqprof2, :freqprof3, :fuma, :fuma15, :fuma18, :fumadia, :fumardoenca, :fxid, :idtrab15, :idtrab18, :informal, :jatrab, :jornada30, :jornada40, :jornadanot, :lixo, :luz, :mcp, :mcpint, :medico, :mobilidade, :moto, :mudar, :naofumamais, :naoquerparar, :ncompfund1, :ncompfund2, :ncompmed, :ncompsup, :nestnpea, :nestnpeanafaz, :nestnpeanfil, :nestnpeanfilnafaz, :nestntrab, :nestntrabnafaz, :nestntrabnfil, :nfcompfund1n2, :nfcompfundnfm, :nfcompmednfs, :nfezativ, :nfncompfund1, :nfncompfund2, :nfncompmed, :nfreq, :nocup, :npea, :nsolteiro, :nuncafumou, :nvontadeprop, :ocup, :ocup2anos, :ocupano, :ocupano2, :outropar, :outrotrab, :outtrabocup, :outtrabocup2, :pc2, :pea, :planosaude, :pob, :procatend, :proctrabocup, :recebatend, :sal1, :sal2, :saudebom, :scardom, :seg, :segbairro, :segcasa, :segcid, :sexo, :sind, :tel, :telc, :tentouparar, :termfund, :termmed, :termsup, :tfn, :tipo, :trabnrem, :tv, :tv2, :tvrad, :univ, :utilint3, :v0102, :violencia, :vitima, :vitimapoli, :vivfilest, :vivfilestaf, :vivfilnest, :vivfilnestaf, :vivfilnocup, :vivfilnocupaf, :vivfilnocupnest, :vivfilnocupnestaf, :vivfilocup, :vivfilocupaf, :vivfilocupest, :vivfilocupestaf

  FONTE = { "PNAD" => 0 }

  #FXID = { "De 15 a 24 Anos" => 1524, "De 15 a 29 Anos" => 1529, "De 18 a 29 Anos" => 1829, "De 15 a 17 Anos" => 1517,
  #         "De 18 a 21 Anos" => 1821, "De 18 a 24 Anos" => 1824, "De 25 a 29 Anos" => 2529 }

  FXID = { "Total (Idade)"   => 9999,
           "De 15 a 17 Anos" => 1517,
           "De 18 a 24 Anos" => 1824,
           "De 25 a 29 Anos" => 2529 }

  UNIV = { "Brasil" => 0, "Norte" => 10, "Nordeste" => 20, "Sudeste" => 30, "Sul" => 40,
           "Centro Oeste" => 49, "Acre" => 12, "Alagoas" => 27, "Amapá" => 16, "Amazonas" => 13, "Bahia" => 29,
           "Ceará" => 23, "Distrito Federal" => 53, "Espirito Santo" => 32, "Goiás" => 52, "Maranhão" => 21,
           "Mato Grosso" => 51, "Mato Grosso do Sul" => 50, "Minas Gerais" => 31, "Pará" => 15, "Paraíba" => 25,
           "Paraná" => 41, "Pernambuco" => 26, "Piauí" => 22, "Rio de Janeiro" => 33, "Rio Grande do Norte" => 24,
           "Rio Grande do Sul" => 43, "Rondônia" => 11, "Roraima" => 14, "Santa Catarina" => 42, "São Paulo" => 35,
           "Sergipe" => 28, "Tocantins" => 17 }

  TIPO = { "Porcentagem"  => 1, "Absoluto" => 2 }
  AREA = { "Total (Área)" => 0, "Urbana"   => 1, "Rural"    => 2 }
  SEXO = { "Total (Sexo)" => 0, "Homens"   => 1, "Mulheres" => 2}
  COR  = { "Total (Cor)"  => 0, "Branco(a)s ou Amarelo(a)s" => 1, "Negro(a)s" => 2 }

  TIPO_GRAFICO = { "Coluna" => "column", "Barra" => "bar", "Linha" => "line", "Área" => 'area'}

  # GRUPO = { "Ano" => "ano", "Sexo" => "sexo", "Cor" => "cor" }
  GRUPO = { "Ano" => "ano" }

  OBJETIVO = {
              "Taxa de analfabetismo" => "analf",
              "Média de anos de estudo dos jovens (em anos de estudo)" => "educa",
              "Porcentagem de jovens que frequentam a escola" => "freq",
              "Porcentagem de jovens não frequentam a escola" => "nfreq",
              "Porcentagem de jovens que frequentam o ensino fundamental" => "freqfund",
              "Porcentagem de jovens que frequentam os anos iniciais do ensino fundamental" => "freqfund1",
              "Porcentagem de jovens que frequentam os anos finais do ensino fundamental" => "freqfund2",
              "Porcentagem de jovens que ainda não completaram as séries iniciais do ensino fundamental" => "ncompfund1",
              "Porcentagem de jovens que ainda não completaram as séries finais do ensino fundamental" => "ncompfund2",
              "Porcentagem de jovens que não estudam, nem completaram os anos iniciais do ensino fundamental" => "nfncompfund1",
              "Porcentagem de jovens que não estudam, completaram os anos iniciais do ensino fundamental, mas não frequentaram os anos finais" => "nfncompfund2",
              "Porcentagem de jovens que não estudam, frequentaram os anos finais do fundamental, mas não completaram o ensino fundamental" => "nfcompfund1n2",
              "Porcentagem de jovens que não estudam, completaram o fundamental, mas nunca frequentaram o ensino médio" => "nfcompfundnfm",
              "Porcentagem de jovens que frequentam o ensino médio" => "freqmed",
              "Porcentagem de jovens que frequentam ou já concluíram o ensino médio" => "freqmed2",
              "Porcentagem de jovens que ainda não completaram o ensino médio" => "ncompmed",
              "Porcentagem de jovens que não estudam, frequentaram, mas não completaram o ensino médio" => "nfncompmed",
              "Porcentagem de jovens que não estudam, completaram o ensino médio, mas nunca frequentaram o ensino superior" => "nfcompmednfs",
              "Porcentagem de jovens que frequentam curso de educação profissional" => "freqprof",
              "Porcentagem de jovens que frequentam curso de educação profissional dentre os que frequentam a escola" => "freqprof2",
              "Porcentagem de jovens que frequentam ou já frequentaram curso de educação profissional" => "freqprof3",
              "Porcentagem de jovens que frequentam ou já completaram o ensino superior" => "freqcompsup",
              "Porcentagem de jovens que frequentam ou já concluíram o mestrado ou o doutorado" => "freqcomppos",
              "Porcentagem de jovens que ainda não completaram o ensino superior" => "ncompsup",
              "Porcentagem de jovens que nem estudam, nem trabalham" => "nestntrab",
              "Porcentagem de jovens que nem estudam, nem estão economicamente ativos" => "nestnpea",
              "Porcentagem de jovens mulheres que nem estudam, nem trabalham, nem vivem com filho" => "nestntrabnfil",
              "Porcentagem de jovens mulheres que nem estudam, nem estão economicamente ativa, nem vivem com filho" => "nestnpeanfil",
              "Porcentagem de jovens que nem estudam, nem trabalham, nem realizam mais de 20 horas de afazeres domésticos por semana" => "nestntrabnafaz",
              "Porcentagem de jovens que nem estudam, nem estão economicamente ativo, nem realizam mais de 20 horas de afazeres domésticos por semana" => "nestnpeanafaz",
              "Porcentagem de jovens mulheres que nem estudam, nem estão economicamente ativa nem vivem com filho, nem realizam mais de 20 horas de afazeres domésticos por semana" => "nestnpeanfilnafaz",
              "Porcentagem de jovens que frequentam curso de educação profissional" => "freqprof",
              "Porcentagem de jovens que frequentam curso de educação profissional dentre os que frequentam a escola" => "freqprof2",
              "Porcentagem de jovens que frequentam ou já frequentaram curso de educação profissional" => "freqprof3",
              "Porcentagem de jovens economicamente ativos" => "pea",
              "Porcentagem de jovens ocupados no ano que começaram a trabalhar antes dos 15 anos" => "idtrab15",
              "Porcentagem de jovens ocupados no ano que começaram a trabalhar antes dos 18 anos" => "idtrab18",
              "Taxa de desemprego de jovens (na semana)" => "dese",
              "Taxa de desemprego de jovens (no mês)" => "desemes",
              "Taxa de desemprego de jovens (no ano) (incluir ocupados no ano)" => "deseano",
              "Porcentagem de jovens ocupados" => "ocup",
              "Porcentagem de jovens que trabalham ou trabalharam no ano" => "ocupano",
              "Porcentagem de jovens que trabalham, trabalharam no ano ou já trabalharam antes" => "jatrab",
              "Porcentagem de jovens que trabalharam no ano, mas que não trabalham na semana" => "ocupano2",
              "Porcentagem de jovens ocupados que procuraram trabalho na semana" => "proctrabocup",
              "Porcentagem de jovens ocupados que já tiveram outro trabalho no ano" => "outtrabocup",
              "Porcentagem de jovens ocupados que já tiveram ao menos outros dois trabalhos no ano" => "outtrabocup2",
              "Porcentagem de jovens ocupados que estão no trabalho atual há menos de dois anos" => "ocup2anos",
              "Porcentagem de jovens ocupados que são empregados domésticos" => "empdom",
              "Porcentagem de jovens ocupados que são empregados sem carteira ou no trabalho doméstico" => "scardom",
              "Porcentagem de jovens ocupados que são trabalhadores por conta-própria sem contribuição à previdência ou afiliação sindical" => "cprop",
              "Porcentagem de jovens que são trabalhadores informais (categorias acima)" => "informal",
              "Porcentagem dos jovens ocupados que são trabalhadores não remunerados" => "trabnrem",
              "Porcentagem dos jovens com remuneração mensal do trabalho (todos) igual ou inferior a 1 salário mínimo" => "sal1",
              "Porcentagem dos jovens com remuneração mensal do trabalho (todos) igual ou inferior a 2 salários mínimos" => "sal2",
              "Porcentagem dos jovens ocupados que gastam mais de 1 hora para chegar no trabalho" => "desloc1",
              "Porcentagem dos jovens empregados não agro cuja jornada de trabalho não era completamente diurna" => "jornadanot",
              "Porcentagem dos jovens ocupados com jornada de trabalho acima de 40 horas" => "jornada40",
              "Porcentagem dos jovens ocupados com jornada de trabalho abaixo de 30 horas" => "jornada30",
              "Porcentagem de jovens que não estão ocupados" => "nocup",
              "Porcentagem de jovens que não estão economicamente ativos" => "npea",
              "Porcentagem de jovens que nem estudam, nem trabalham" => "nestntrab",
              "Porcentagem de jovens que nem estudam, nem estão economicamente ativos" => "nestnpea",
              "Porcentagem de jovens mulheres que nem estudam, nem trabalham, nem vivem com filho" => "nestntrabnfil",
              "Porcentagem de jovens mulheres que nem estudam, nem estão economicamente ativas, nem vivem com filho" => "nestnpeanfil",
              "Porcentagem de jovens que realizam mais de 20 horas a afazeres domésticos por semana" => "afaz20",
              "Porcentagem de jovens que nem estudam, nem trabalham, nem realizam mais de 20 horas de afazeres domésticos por semana" => "nestntrabnafaz",
              "Porcentagem de jovens que nem estudam, nem estão economicamente ativos, nem realizam mais de 20 horas de afazeres domésticos por semana" => "nestnpeanafaz",
              "Porcentagem de jovens mulheres que nem estudam, nem estão economicamente ativas nem vivem com filho, nem realizam mais de 20 horas de afazeres domésticos por semana." => "nestnpeanfilnafaz",
              "Porcentagem de jovens que vivem em famílias com renda abaixo de R$70" => "extpob",
              "Porcentagem de jovens que vivem em famílias com renda abaixo de R$140" => "pob",
              "Porcentagem de jovens que vivem em famílias da classe baixa" => "cb",
              "Porcentagem de jovens que vivem em famílias da classe média" => "cm",
              "Porcentagem de jovens com insegurança alimentar segundo a EBIA" => "alim",
              "Porcentagem de jovens que consideram seu estado de saúde bom ou muito bom" => "saudebom",
              "Porcentagem de jovens que consultaram médico no último ano" => "medico",
              "Porcentagem de jovens que foram ao dentista no último ano" => "dentista",
              "Porcentagem de jovens que procuraram atendimento de saúde nas últimas duas semanas" => "procatend",
              "Porcentagem de jovens que receberam o 1º atendimento dentre os que procuraram nas últimas duas semanas" => "recebatend",
              "Porcentagem de jovens que praticam esporte" => "esporte",
              "Porcentagem de jovens que praticam esporte mais de 2 dias por semana" => "esporte2",
              "Porcentagem de jovens que estiveram acamados" => "acamados",
              "Porcentagem de jovens que têm alguma doença crônica" => "cronica",
              "Porcentagem de jovens que deixaram de realizar atividades por motivo de saúde" => "nfezativ",
              "Porcentagem de jovens cobertos por plano de saúde" => "planosaude",
              "Porcentagem de jovens que nunca fumaram" => "nuncafumou",
              "Porcentagem de jovens que fumam atualmente" => "fuma",
              "Porcentagem de jovens que fumam diariamente" => "fumadia",
              "Porcentagem de jovens que começaram a fumar antes dos 15 anos" => "fuma15",
              "Porcentagem de jovens que começaram a fumar antes dos 18 anos" => "fuma18",
              "Porcentagem de jovens dos que fumam que tentaram parar de fumar no último ano" => "tentouparar",
              "Porcentagem de jovens dos que fumam que não têm interesse em parar de fumar" => "naoquerparar",
              "Porcentagem de jovens dos que já fumaram e que não fumam mais, que pararam de fumar a menos de 1 ano" => "naofumamais",
              "Porcentagem de jovens que acreditam que fumar causa doença grave" => "fumardoenca",
              "Porcentagem de jovens que é pessoa de referência ou cônjuge do domicílio" => "chefeconj",
              "Porcentagem de jovens que são filhos da pessoa de referência do domicílio" => "filho",
              "Porcentagem de jovens que são outros parentes ou agregados da pessoa de referência do domicílio" => "outropar",
              "Porcentagem que vivem em família convivente" => "famconviv",
              "Porcentagem das pessoas de referência de família convivente que não vivem no domicílio por vontade própria" => "nvontadeprop",
              "Porcentagem das pessoas de referência de família convivente que têm a intenção de mudar ou constituir outro domicílio" => "mudar",
              "Porcentagem de jovens que não são solteiros" => "nsolteiro",
              "Porcentagem das jovens mulheres que já tiveram filho (7 meses de gestação ou nascido vivo ou morto)" => "tfn",
              "Porcentagem de jovens que vivem em domicílios com TV" => "tv",
              "Porcentagem de jovens que vivem em domicílios com TV ou rádio" => "tvrad",
              "Porcentagem de jovens que vivem em domicílios com DVD" => "dvd",
              "Porcentagem de jovens com celular" => "telc",
              "Porcentagem de jovens com celular de uso pessoal" => "celpess",
              "Porcentagem de jovens que vivem em domicílios com telefone fixo" => "tel",
              "Porcentagem de jovens que vivem em domicílios com computador" => "mcp",
              "Porcentagem de jovens que vivem em domicílios com computador com acesso à Internet" => "mcpint",
              "Porcentagem de jovens que vêem mais de 2 horas de TV por dia" => "tv2",
              "Porcentagem de jovens que usaram o computador ou vídeo game mais de 2 horas por dia" => "pc2",
              "Porcentagem de jovens que utilizaram internet nos últimos 3 meses" => "utilint3",
              "Porcentagem de jovens com carro ou moto de uso pessoal" => "moto",
              "Porcentagem de jovens com alguma dificuldade física de mobilidade" => "mobilidade",
              "Porcentagem de jovens com acesso adequado à água" => "agua",
              "Porcentagem de jovens com acesso adequado a saneamento" => "esco",
              "Porcentagem de jovens com acesso adequado à água e a saneamento" => "aguaesco",
              "Porcentagem de jovens com acesso adequado à coleta de lixo" => "lixo",
              "Porcentagem de jovens com acesso adequado à água, saneamento e coleta de lixo" => "aguaescolixo",
              "Porcentagem de jovens em habitações com no máximo dois moradores por dormitório" => "dens",
              "Porcentagem de jovens com acesso à energia elétrica" => "luz",
              "Porcentagem de jovens que têm algum dispositivo de segurança, exceto cachorro" => "seg",
              "Porcentagem de jovens que se sentem seguros em casa" => "segcasa",
              "Porcentagem de jovens que se sentem seguros no bairro" => "segbairro",
              "Porcentagem de jovens que se sentem seguros na cidade" => "segcid",
              "Porcentagem de jovens vítimas de tentativa de furto, furto, roubo ou agressão física" => "vitima",
              "Porcentagem dos jovens que foram vítimas de furto, roubo ou agressão física que procuraram a polícia (se mais de um, basta ter procurado em um dos casos)" => "vitimapoli",
              "Porcentagem de jovens que tiveram conflito" => "conflito",
              "Porcentagem de jovens com conflito que procurou solução na justiça, juizado, Procon ou polícia" => "conflitosol",
              "Porcentagem de jovens vítimas de violência" => "violencia",
              "Porcentagem de jovens vítimas de acidente de trânsito" => "acidente",
              "Porcentagem de jovens que concluíram o ensino fundamental" => "termfund",
              "Porcentagem de jovens que concluíram o ensino médio" => "termmed",
              "Porcentagem de jovens que concluíram o ensino superior" => "termsup",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e trabalham" => "vivfilocup",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e não trabalham" => "vivfilnocup",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e estudam" => "vivfilest",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e não esudam" => "vivfilnest",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e trabalham e estudam" => "vivfilocupest",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho e não trabalham nem estudam" => "vivfilnocupnest",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e trabalham" => "vivfilocupaf",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e não trabalham" => "vivfilnocupaf",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e estudam" => "vivfilestaf",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e não esudam" => "vivfilnestaf",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e trabalham e estudam" => "vivfilocupestaf",
              "Porcentagem de jovens que são chefes ou cônjuges da família que vivem com o filho, realizam afazeres domésticos, e não trabalham nem estudam" => "vivfilnocupnestaf",
              "Porcentagem de jovens que são filiados a algum sindicato, entre os que trabalharam no último ano" => "sind",
              "Porcentagem de jovens ocupados na semana em mais de um trabalho" => "outrotrab"
            }
end
